MacaroonError: add trait impl; docs; tests
Adds trait implementations for std::error::Error and std::fmt::Display,
which are best practice for any publicly-exposed error types.

Adds documentation to the MacaroonError type.

Adds some basic test coverage for some of the errors, confirming that
the specific variants are raised as expected.